language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  - EnmTransformerTestCase

before_script:
  - composer self-update
  - composer install

script: php vendor/bin/phpunit -c phpunit.xml.dist --coverage-text

notifications:
  email:
    - bogomolov@eosnewmedia.de
    - marien@eosnewmedia.de
